### ISSUE TITLE
The file assets/stylesheet.css seems not to be used

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMet4FoF#11]
A full-text search for the filename of [assets/stylesheet.css](https://github.com/bangxiangyong/agentMet4FoF/blob/master/assets/stylesheet.css) in the project gave no results. After deleting it, all tests and examples still succeeded. Can that file maybe be deleted?

**Comment by bangxiangyong** [comment]
The dash package automatically serves files in the assets folder when serving the dashboard app. Probably that's why it doesn't show up in the code.
[reference](https://dash.plot.ly/dash-deployment-server/static-assets)

For our application, I used it to remove the undo-redo buttons which are embedded in the graphs by default, which I thought appeared to be confusing. [reference](https://community.plot.ly/t/what-exactly-the-undo-redo-buttons-are-for/6546) 

So perhaps it may still be needed..

**Comment by BjoernLudwigPTB** [comment]
Ah, alright... it only seems not to be used... I suggest to move the _assets_ folder then into the _dashboard_ folder, because it strictly belongs to it and keeps the root folder a little cleaner.

**Comment by bangxiangyong** [comment]
Yes, you're right, that makes sense..
