### ISSUE TITLE
We should think about a way how to make debugging possible

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#81]
Because of the subprocesses we are spawning, in general debugging does not work as usual. We should think about, if it is possible to make that available. It would strip a lot of print statements from the codes we are seeing being written using the agents and make debugging a lot easier.

**Comment by bangxiangyong** [comment]
yes, i'm wondering how the osbrain guys do it as well..

**Comment by BjoernLudwigPTB** [comment]
Steps to take then:

- [ ] check how [osbrain](https://github.com/opensistemas-hub/osbrain) is doing it
- [ ] ...

**Comment by bangxiangyong** [comment]
Apparently the guys at osbrain have not implemented how to attach a debugger yet. The way they handled it is described here: https://github.com/opensistemas-hub/osbrain/issues/360

**Comment by BjoernLudwigPTB** [comment]
#113 would make this obsolete, right? We should first deal with the considerations regarding the backend change, before we keep thinking about this.

**Comment by bangxiangyong** [comment]
i figured one way to do it with pycharm is via 'Attach a debugger to Process' via Ctrl+Shift+A
after the agents are launched, we can attach a debugger to individual agent, and i manage to stop at a breakpoint and inspect the sine genrator agent's loop.  

however, since the processes have different names , we may not be able to tell which process belongs to which agent. some exploration is needed for a smoother debugging experience..

**Comment by BjoernLudwigPTB** [comment]
That sounds just like what I imagined. Maybe it would help to record the subprocesses [name](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.name) or [id](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.pid) when spawning it.
